# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'dev'
    version: 'latest'

# - task: FlutterCommand@0
#   inputs:
#     arguments: 'build windows --release'

- task: FlutterCommand@0
  inputs:
    arguments: 'config --enable-macos-desktop'

- task: FlutterCommand@0
  inputs:
    arguments: 'config --enable-linux-desktop'

- task: FlutterCommand@0
  inputs:
    arguments: 'build macos --release'

- task: FlutterCommand@0
  inputs:
    arguments: 'build linux --release'
- task: FlutterCommand@0
  inputs:
    arguments: 'build web --release'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      echo 'building flutter apps...'
      $(FlutterToolPath) build macos --release
      $(FlutterToolPath) build linux --release
      $(FlutterToolPath) build web --release
- task: CopyFiles@2
  inputs:
    SourceFolder: 'macos'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/macos'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/linux'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'