# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'dev'
    version: 'latest'

# - task: FlutterCommand@0
#   inputs:
#     arguments: 'build windows --release'

- task: FlutterCommand@0
  inputs:
    arguments: 'config --enable-macos-desktop'

- task: FlutterCommand@0
  inputs:
    arguments: 'config --enable-linux-desktop'

- task: FlutterCommand@0
  inputs:
    arguments: 'build macos --release'

- task: FlutterCommand@0
  inputs:
    arguments: 'build linux --release'
