# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'dev'
    version: 'latest'

# - task: FlutterCommand@0
#   inputs:
#     arguments: 'build windows --release'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      $(FlutterToolPath)/flutter config --enable-macos-desktop
      $(FlutterToolPath)/flutter config --enable-linux-desktop
      $(FlutterToolPath)/flutter config --enable-web
      
      echo 'building flutter apps...'
      $(FlutterToolPath)/flutter build macos --release
      $(FlutterToolPath)/flutter build linux --release
      $(FlutterToolPath)/flutter build web --release
- task: CopyFiles@2
  inputs:
    SourceFolder: 'macos'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/macos'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/linux'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'