# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool:
  vmImage: 'macos-latest'

steps:
- task: FlutterInstall@0
  inputs:
    channel: 'dev'
    version: 'latest'

# - task: FlutterCommand@0
#   inputs:
#     arguments: 'build windows --release'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export PATH="$PATH:`pwd`$(FlutterToolPath)"
      echo 'PATH is set to'
      echo $PATH
      # Write your commands here
      flutter config --enable-macos-desktop
      flutter config --enable-linux-desktop
      flutter config --enable-web
      
      echo 'building flutter apps...'
      flutter build macos --release
      flutter build linux --release
      flutter build web --release
- task: CopyFiles@2
  inputs:
    SourceFolder: 'macos'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/macos'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'linux'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/linux'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'web'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/web'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'